// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && (386 || amd64)

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ollyAcceptArgs struct {
	_    structs.HostLayout
	Addr uint64
}

type ollyConnKey struct {
	_   structs.HostLayout
	Pid uint32
	Fd  int32
}

type ollyConnVal struct {
	_    structs.HostLayout
	Addr uint32
	Port uint16
	Dir  uint8
	Pad  uint8
}

type ollyConnectArgs struct {
	_    structs.HostLayout
	Addr uint64
	Fd   int32
	_    [4]byte
}

type ollyEphPortKey struct {
	_          structs.HostLayout
	Pid        uint32
	RemoteAddr uint32
	RemotePort uint16
	Pad        uint16
}

type ollyEphPortVal struct {
	_         structs.HostLayout
	LocalPort uint16
	Pad       uint16
	_         [4]byte
	Cookie    uint64
}

type ollyPidCtx struct {
	_           structs.HostLayout
	Ctx         ollyTraceCtx
	TimestampNs uint64
	InboundFd   uint32
	Concurrent  uint8
	Pad2        [3]uint8
}

type ollyRwArgs struct {
	_     structs.HostLayout
	Buf   uint64
	Fd    int32
	Count uint32
	Flags uint32
	_     [4]byte
}

type ollySockKey struct {
	_       structs.HostLayout
	SrcIp   [4]uint32
	DstIp   [4]uint32
	SrcPort uint32
	DstPort uint32
}

type ollySslRwArgs struct {
	_      structs.HostLayout
	Buf    uint64
	Len    uint32
	_      [4]byte
	SslPtr uint64
}

type ollyThreadKey struct {
	_   structs.HostLayout
	Pid uint32
	Tid uint32
}

type ollyTraceCtx struct {
	_         structs.HostLayout
	Valid     uint8
	Pad       [3]uint8
	HeaderLen uint32
	Header    [71]int8
	_         [1]byte
}

// loadOlly returns the embedded CollectionSpec for olly.
func loadOlly() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OllyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load olly: %w", err)
	}

	return spec, err
}

// loadOllyObjects loads olly and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ollyObjects
//	*ollyPrograms
//	*ollyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOllyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOlly()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ollySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ollySpecs struct {
	ollyProgramSpecs
	ollyMapSpecs
	ollyVariableSpecs
}

// ollyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ollyProgramSpecs struct {
	KprobeAccept               *ebpf.ProgramSpec `ebpf:"kprobe_accept"`
	KprobeAccept4              *ebpf.ProgramSpec `ebpf:"kprobe_accept4"`
	KprobeClose                *ebpf.ProgramSpec `ebpf:"kprobe_close"`
	KprobeConnect              *ebpf.ProgramSpec `ebpf:"kprobe_connect"`
	KprobeRead                 *ebpf.ProgramSpec `ebpf:"kprobe_read"`
	KprobeRecvfrom             *ebpf.ProgramSpec `ebpf:"kprobe_recvfrom"`
	KprobeSendto               *ebpf.ProgramSpec `ebpf:"kprobe_sendto"`
	KprobeWrite                *ebpf.ProgramSpec `ebpf:"kprobe_write"`
	KretprobeAccept            *ebpf.ProgramSpec `ebpf:"kretprobe_accept"`
	KretprobeAccept4           *ebpf.ProgramSpec `ebpf:"kretprobe_accept4"`
	KretprobeConnect           *ebpf.ProgramSpec `ebpf:"kretprobe_connect"`
	KretprobeRead              *ebpf.ProgramSpec `ebpf:"kretprobe_read"`
	KretprobeRecvfrom          *ebpf.ProgramSpec `ebpf:"kretprobe_recvfrom"`
	OllySkMsg                  *ebpf.ProgramSpec `ebpf:"olly_sk_msg"`
	OllySockops                *ebpf.ProgramSpec `ebpf:"olly_sockops"`
	TracepointInetSockSetState *ebpf.ProgramSpec `ebpf:"tracepoint_inet_sock_set_state"`
	TracepointSchedProcessExec *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_exec"`
	UprobeSslRead              *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslSetFd             *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_fd"`
	UprobeSslWrite             *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UretprobeSslRead           *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslWrite          *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write"`
}

// ollyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ollyMapSpecs struct {
	AcceptArgsMap  *ebpf.MapSpec `ebpf:"accept_args_map"`
	ConnMap        *ebpf.MapSpec `ebpf:"conn_map"`
	ConnectArgsMap *ebpf.MapSpec `ebpf:"connect_args_map"`
	EphPortMap     *ebpf.MapSpec `ebpf:"eph_port_map"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	LogFdMap       *ebpf.MapSpec `ebpf:"log_fd_map"`
	PidCtxScratch  *ebpf.MapSpec `ebpf:"pid_ctx_scratch"`
	PidFilter      *ebpf.MapSpec `ebpf:"pid_filter"`
	PidTraceCtx    *ebpf.MapSpec `ebpf:"pid_trace_ctx"`
	RwArgsMap      *ebpf.MapSpec `ebpf:"rw_args_map"`
	SkPidMap       *ebpf.MapSpec `ebpf:"sk_pid_map"`
	SockOpsMap     *ebpf.MapSpec `ebpf:"sock_ops_map"`
	SslFdMap       *ebpf.MapSpec `ebpf:"ssl_fd_map"`
	SslRwArgsMap   *ebpf.MapSpec `ebpf:"ssl_rw_args_map"`
	ThreadTraceCtx *ebpf.MapSpec `ebpf:"thread_trace_ctx"`
	TracingEnabled *ebpf.MapSpec `ebpf:"tracing_enabled"`
}

// ollyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ollyVariableSpecs struct {
}

// ollyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOllyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ollyObjects struct {
	ollyPrograms
	ollyMaps
	ollyVariables
}

func (o *ollyObjects) Close() error {
	return _OllyClose(
		&o.ollyPrograms,
		&o.ollyMaps,
	)
}

// ollyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOllyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ollyMaps struct {
	AcceptArgsMap  *ebpf.Map `ebpf:"accept_args_map"`
	ConnMap        *ebpf.Map `ebpf:"conn_map"`
	ConnectArgsMap *ebpf.Map `ebpf:"connect_args_map"`
	EphPortMap     *ebpf.Map `ebpf:"eph_port_map"`
	Events         *ebpf.Map `ebpf:"events"`
	LogFdMap       *ebpf.Map `ebpf:"log_fd_map"`
	PidCtxScratch  *ebpf.Map `ebpf:"pid_ctx_scratch"`
	PidFilter      *ebpf.Map `ebpf:"pid_filter"`
	PidTraceCtx    *ebpf.Map `ebpf:"pid_trace_ctx"`
	RwArgsMap      *ebpf.Map `ebpf:"rw_args_map"`
	SkPidMap       *ebpf.Map `ebpf:"sk_pid_map"`
	SockOpsMap     *ebpf.Map `ebpf:"sock_ops_map"`
	SslFdMap       *ebpf.Map `ebpf:"ssl_fd_map"`
	SslRwArgsMap   *ebpf.Map `ebpf:"ssl_rw_args_map"`
	ThreadTraceCtx *ebpf.Map `ebpf:"thread_trace_ctx"`
	TracingEnabled *ebpf.Map `ebpf:"tracing_enabled"`
}

func (m *ollyMaps) Close() error {
	return _OllyClose(
		m.AcceptArgsMap,
		m.ConnMap,
		m.ConnectArgsMap,
		m.EphPortMap,
		m.Events,
		m.LogFdMap,
		m.PidCtxScratch,
		m.PidFilter,
		m.PidTraceCtx,
		m.RwArgsMap,
		m.SkPidMap,
		m.SockOpsMap,
		m.SslFdMap,
		m.SslRwArgsMap,
		m.ThreadTraceCtx,
		m.TracingEnabled,
	)
}

// ollyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOllyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ollyVariables struct {
}

// ollyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOllyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ollyPrograms struct {
	KprobeAccept               *ebpf.Program `ebpf:"kprobe_accept"`
	KprobeAccept4              *ebpf.Program `ebpf:"kprobe_accept4"`
	KprobeClose                *ebpf.Program `ebpf:"kprobe_close"`
	KprobeConnect              *ebpf.Program `ebpf:"kprobe_connect"`
	KprobeRead                 *ebpf.Program `ebpf:"kprobe_read"`
	KprobeRecvfrom             *ebpf.Program `ebpf:"kprobe_recvfrom"`
	KprobeSendto               *ebpf.Program `ebpf:"kprobe_sendto"`
	KprobeWrite                *ebpf.Program `ebpf:"kprobe_write"`
	KretprobeAccept            *ebpf.Program `ebpf:"kretprobe_accept"`
	KretprobeAccept4           *ebpf.Program `ebpf:"kretprobe_accept4"`
	KretprobeConnect           *ebpf.Program `ebpf:"kretprobe_connect"`
	KretprobeRead              *ebpf.Program `ebpf:"kretprobe_read"`
	KretprobeRecvfrom          *ebpf.Program `ebpf:"kretprobe_recvfrom"`
	OllySkMsg                  *ebpf.Program `ebpf:"olly_sk_msg"`
	OllySockops                *ebpf.Program `ebpf:"olly_sockops"`
	TracepointInetSockSetState *ebpf.Program `ebpf:"tracepoint_inet_sock_set_state"`
	TracepointSchedProcessExec *ebpf.Program `ebpf:"tracepoint_sched_process_exec"`
	UprobeSslRead              *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslSetFd             *ebpf.Program `ebpf:"uprobe_ssl_set_fd"`
	UprobeSslWrite             *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UretprobeSslRead           *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslWrite          *ebpf.Program `ebpf:"uretprobe_ssl_write"`
}

func (p *ollyPrograms) Close() error {
	return _OllyClose(
		p.KprobeAccept,
		p.KprobeAccept4,
		p.KprobeClose,
		p.KprobeConnect,
		p.KprobeRead,
		p.KprobeRecvfrom,
		p.KprobeSendto,
		p.KprobeWrite,
		p.KretprobeAccept,
		p.KretprobeAccept4,
		p.KretprobeConnect,
		p.KretprobeRead,
		p.KretprobeRecvfrom,
		p.OllySkMsg,
		p.OllySockops,
		p.TracepointInetSockSetState,
		p.TracepointSchedProcessExec,
		p.UprobeSslRead,
		p.UprobeSslSetFd,
		p.UprobeSslWrite,
		p.UretprobeSslRead,
		p.UretprobeSslWrite,
	)
}

func _OllyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed olly_x86_bpfel.o
var _OllyBytes []byte
